Lesson9 ajax 2
ruslan-yandiev/qna pull request #7
Opened 2020-09-16 23:33 UTC by ruslan-yandiev

2020-09-17 10:24 UTC, IvanShamatov requested changes

2020-09-17 10:24 UTC, IvanShamatov commented on app/controllers/answers_controller.rb
> +    # а значит проигнорирует связанный с этим экшеном вьюху create.js.erb
откуда такая информация? Рельса выберет create.js.erb если ты напишешь обработчик формата
format.js { }

2020-09-17 10:24 UTC, IvanShamatov commented on app/controllers/concerns/voted.rb
> +    return head :forbidden if current_user&.author?(@resource)
для голосования абсолютно точно нужно иметь пользователя до этого. Поэтому проверка на то, что пользователь не существует -- не нужна.

2020-09-17 10:24 UTC, IvanShamatov commented on app/controllers/concerns/voted.rb
> +    before_action :resource, only: %i[voteup votedown]
before_action :authenticate_user! вот этой строчки здесь не хватает

2020-09-17 10:24 UTC, IvanShamatov commented on app/models/concerns/votable.rb
> +    return if votes.find_by(value: -1, user: user)&.delete
ахах. ну ладно. жизнеспособно

2020-09-17 10:24 UTC, IvanShamatov commented on app/views/answers/_form.html.slim
> += form_with model: [question, answer], class: "answer-create", data: { type: :json } do |form|
выглядит так, будто у тебя просто не получилось завести create.js.erb, поэтому ты тут тип передаешь

2020-09-17 11:43 UTC, ruslan-yandiev commented on app/views/answers/_form.html.slim
> += form_with model: [question, answer], class: "answer-create", data: { type: :json } do |form|
Вьюху create.js.erb, мы же заводили в ранее пройденных уроках и она успешно работала ))
Это я так, оставил себе напоминалку, так-как ранее никогда не передавал данные в других форматах кроме html и JS

2020-09-17 11:47 UTC, ruslan-yandiev commented on app/controllers/concerns/voted.rb
> +    return head :forbidden if current_user&.author?(@resource)
Тут я пытался реализовать то, что если текущий пользователь является автором ресурса, то он не сможет проголосовать и вернется ошибка со статусом 403. Или я не правильно это реализовал?

2020-09-17 11:58 UTC, ruslan-yandiev commented on app/controllers/answers_controller.rb
> +    # а значит проигнорирует связанный с этим экшеном вьюху create.js.erb
Как я понял при реализации format.js { } контроллер будет искать вьюху create.js.erb для отображения, если же ее не найдет, то все равно вернет данные в формате js, однако браузер получив эти данные не будет знать, что с ними делать. Соответственно это мы увидим во вкладке браузера Network. Также контроллер будет использовать вьюху create.js.erb если никакие форматы не заданы. Или я, что-то не так понял?

2020-09-18 06:01 UTC, IvanShamatov commented on app/views/answers/_form.html.slim
> += form_with model: [question, answer], class: "answer-create", data: { type: :json } do |form|
и все же я не совсем понимаю, в чем поинт в этой задаче использовать формат json

2020-09-18 06:04 UTC, IvanShamatov commented on app/controllers/concerns/voted.rb
> +    before_action :authenticate_user!, except: %i[index show]
знаешь, стало хуже. поскольку модуль теперь почему-то еще и влияет на логику контроллера, а не только свою. Пусть аутентификация останется в контроллерах, и оставим safe оператор в voteup и votedown

2020-09-18 06:05 UTC, IvanShamatov commented on app/models/concerns/votable.rb
> +  def all_likes
давай назовем это просто votes

2020-09-18 06:08 UTC, IvanShamatov commented on app/views/answers/_answer.html.slim
> +      / если форма или ссылка не содержит по дефолту как form_with опцию отправки с помощью Ajax, то можно установить такую опцию вручную добавив remote: true
добавим сюда, что это работает с помощью турболинкс. Без них remote: true на ссылках работать не будет

2020-09-18 11:12 UTC, vkurennov commented on app/controllers/concerns/voted.rb
> +    return head :forbidden if current_user&.author?(@resource)
Иван имел в виду, что не нужен `&.`, т.к. он уже точно должен быть на этот момент

2020-09-18 11:19 UTC, vkurennov approved these changes

2020-09-18 11:19 UTC, vkurennov commented on app/views/answers/_form.html.slim
> += form_with model: [question, answer], class: "answer-create", data: { type: :json } do |form|
@IvanShamatov это требования задания ))

2020-09-18 13:34 UTC, ruslan-yandiev commented
Используя JSON, реализовать следующие истории:
 
 - Аутентифицированный пользователь может голосовать за понравившийся вопрос/ответ
 - Пользователь не может голосовать за свой вопрос/ответ
 - Пользователь может проголосовать "за" или "против" конкретного вопроса/ответа только один раз (нельзя голосовать 2 раза подряд "за" или "против")
 - Пользователь может отменить свое решение и после этого переголосовать.
 - У вопроса/ответа должен выводиться результирующий рейтинг (разница между голосами "за" и "против")

При реализации голосования запрещено использовать сторонние гемы для этого функционала

Рекомендации:
 - Реализовать возможность голосования через консерны.

2020-09-18 13:34 UTC, merged